#!/bin/bash

API_URL="http://localhost:8080/api/v1"
REGISTER_URL="auth/register"
LOGIN_URL="auth/login"

# Генерация данных пользователя
PASSWORD="password${RANDOM}"
EMAIL="user${RANDOM}@example.com"

# Отправляем POST-запрос для регистрации пользователя
RESPONSE=$(curl -s -X POST $API_URL/$REGISTER_URL \
        -H "Content-Type: application/json" \
        -d '{
        "email": "'$EMAIL'",
        "password": "'$PASSWORD'",
        "firstname": "Oleg",
        "lastname": "Safronov",
        "birthday": "18-10-2004",
        "gender": "Male"
}')

# Проверяем, успешна ли регистрация
if [[ $(echo $RESPONSE | jq -r '.message') != "User registered successfully" ]]; then
    echo $RESPONSE | jq
    exit 1
fi

# Отправляем POST-запрос для авторизации пользователя
RESPONSE=$(curl -s -X POST $API_URL/$LOGIN_URL \
        -H "Content-Type: application/json" \
        -d '{
        "email": "'$EMAIL'",
        "password": "'$PASSWORD'"
}')

# Проверяем, успешна ли авторизация
if [[ $(echo $RESPONSE | jq -r '.token') == "null" ]]; then
    echo "Failed to login user"
    echo $RESPONSE | jq
    exit 1
fi

echo $RESPONSE | jq
