---
version: '3.9'
name: backend-dev

services:
  web:
    build:
      context: ./app
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - path: ./envs/dev.env
        required: true

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - path: ./envs/dev.env
        required: true

volumes:
  postgres_data:
