---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 80
      targetPort: http
      nodePort: {{ .Values.nodePort }}
---
kind: Service
apiVersion: v1
metadata:
  name: "db"
spec:
  selector:
    app: "postgres"
  ports:
    - port: 5432
      targetPort: db
  clusterIP: 10.254.159.185
