---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.app.image }}
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1024Mi
            cpu: 2
          requests:
            memory: 1024Mi
            cpu: 2
        env:
          - name: "SERVER_PORT"
            value: "{{ .Values.global.app.port }}"
          - name: "DB_HOST"
            value: "{{ .Values.global.db.host }}"
          - name: "DB_PORT"
            value: "{{ .Values.global.db.port }}"
          - name: "DB_NAME"
            value: "{{ .Values.global.db.name }}"
          - name: "DB_USER"
            value: "{{ .Values.global.db.user }}"
          - name: "DB_PASSWORD"
            value: "{{ .Values.global.db.password }}"
        ports:
        - name: http
          containerPort: {{ .Values.global.app.port }}
