---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 80
      targetPort: http
      nodePort: {{ .Values.global.app.nodePort }}
