#!/bin/bash

API_URL="http://localhost:8080/api/v1"
USER_URL="trx"

# Проверка наличия аргумента (токена)
if [ $# -eq 0 ]; then
    echo "Usage: $0 <token>"
    exit 1
fi

TOKEN="$1"

# Отправляем PATCH-запрос
RESPONSE=$(curl -s -X GET $API_URL/$USER_URL \
        -H "Authorization: Bearer $TOKEN")

echo $RESPONSE | jq
